version: '3'
services:
  aspnetcore-in-docker:
    image: aspnetcore-in-docker
    container_name: aspnetcore-in-docker
    ports:
      - 5000:80
    volumes:
      - /c/Users/larry/Downloads/logs.txt:/app/logs.txt